config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'items#index'

  resources :items do
    member do
      get 'confirm'
      post 'pay'
    end
    collection do
    get 'set_parents'
    get 'set_children'
    get 'set_grandchildren'
    end
    resources :images, only: [:new, :create]
  end

  resources :cards, only: [:new, :create, :show, :destroy]


  get 'users', to: 'users#index'

  resources :users, only: [:new, :show] do
    collection do
      get 'user_logout'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
  validates :family_name, :first_name,              format: {with: /\A[ぁ-んァ-ン一-龥]+\z/}, allow_blank: true
  validates :family_name, :first_name, presence: true
  validates :first_name_kana, :family_name_kana,   format: {with: /\A[ァ-ヶー－]+\z/}, allow_blank: true
  validates :first_name_kana, :family_name_kana, presence: true
  validates :birth_year, :birth_month, :birth_day, numericality: { only_integer: true, message: "を選択してください"}
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: "は英字と数字を最低1つ入力してください"}, allow_blank: true
  validates :password, presence: true

  has_many :addresses, dependent: :destroy
  has_many :items,     dependent: :destroy
  has_one  :card,      dependent: :destroy
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    @user = User.new
  end

  def create
    @user = User.new(sign_up_params)
    unless @user.valid?
      flash.now[:alert] = @user.errors.full_messages
      render :new and return
    end
    session["devise.regist_data"] = {user: @user.attributes}
    session["devise.regist_data"][:user]["password"] = params[:user][:password]
    @address = @user.addresses.build
    render :new_address
  end

  def new_address
    if @address == nil
      redirect_to root_path and return
    end
    @user = User.new(session["devise.regist_data"]["user"])
    @address = Address.new
  end

  def create_address
    @user = User.new(session["devise.regist_data"]["user"])
    @address = Address.new(address_params)
    unless @address.valid?
      flash.now[:alert] = @address.errors.full_messages
      render :new_address and return
    end
    @user.addresses.build(@address.attributes)
    @user.save
    session["devise.regist_data"]["user"].clear
    sign_in(:user, @user)
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  def address_params
    params.require(:address).permit(:first_name, :family_name, :first_name_kana, :family_name_kana, :post_code, :prefecture, :city, :address, :apartment, :tel_number)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    redirect_to root_path
  end

  def user_logout
  end
    
  def show
  end
end

app/views/users/_side_bar.html.haml
.side-bar
  .side-bar__navi
    .side-bar__navi__list
      = link_to "マイページ", "#",class: "side-bar__navi__list__menu"
      = link_to "お知らせ", "#", class: "side-bar__navi__list__menu"
      = link_to "やることリスト", "#", class: "side-bar__navi__list__menu"
    %h4.side-bar__navi__title
      クレジットカード
    .side-bar__navi__list
      = link_to "クレジットカード登録・削除", new_card_path, class: "side-bar__navi__list__menu"
    %h4.side-bar__navi__title
      設定
    .side-bar__navi__list
      = link_to "ログアウト", user_logout_users_path, class: "side-bar__navi__list__menu"

app/views/users/new.html.haml
.new-registration__page
  = render "shared/logo"
  .main-block
    .main-block__top
      新規会員登録
    .main-block__bottom
      .main-block__bottom__link
        = link_to new_user_registration_path do
          .main-block__bottom__link__icon
            = icon('far', 'envelope', class: 'icon')
          .main-block__bottom__link__text
            メールアドレスで登録する
  = render "shared/user_footer"

app/views/users/show.html.haml
= render "shared/header"

.wrapper.clearfix
  = render "side_bar"

  .mypage-show
    .user-image
      = image_tag "/member_photo_noimage_thumb.png", size: "100x100", alt: "", class: "user-image__img"
      .user-name
        = link_to current_user.nickname, "#"
      .user-box
        %p.user-box__evaluation
          評価
        .number
          = "#{0}"
        %p.user-box__exhibition
          出品数
        .number
          = "#{0}"
    .todo-box
      %ul.mypage-tabs
        %li.tab.active
          お知らせ
        %li.tab
          やることリスト
      %ul.mypage-panels
        %li.panel.show
          .todos
            -# データの登録ができたらeach文に変更する
            -# @todoes.each do |todo|
            = link_to "#", class: "todo" do
              .todo__img
                = image_tag "/icon_brand.png", size: "40x40", alt: ""
              .todo__body
                .todo__body__text
                  = simple_format "事務局からのメッセージ"
                .todo__body__info
                  .todo__body__info__icon
                    = icon('fa', 'clock')
                  .todo__body__info__num
                    1時間前
              .todo__right-icon
                = icon('fa','angle-right')
        %li.panel
    .purchase-product
      %h3.purchase-product__title
        購入した商品
      %ul.mypage-tabs
        %li.tab.active
          取引中
        %li.tab
          過去の取引
      %ul.mypage-panels
        %li.panel.show
          .items
            = link_to "#", class: "item" do
              .item__img
                = image_tag "/icon_brand.png", size: "40x40", alt: ""
              .item__body
                .item__body__text
                  = simple_format "（仮）テレビを購入"
                .item__body__info
                  %p.repuired
                    （仮）発送完了
              .item__right-icon
                = icon('fa','angle-right')
        %li.panel
    .listing-product
      %h3.listing-product__title
        出品した商品
      %ul.mypage-tabs
        %li.tab.active
          出品中
        %li.tab
          取引中
        %li.tab
          売却済み
      %ul.mypage-panels
        %li.panel.show
          .items
            = link_to "#", class: "item" do
              .item__img
                = image_tag "/icon_brand.png", size: "40x40", alt: ""
              .item__body
                .item__body__text
                  = simple_format "（仮）パソコンを出品"
                .item__body__info
                  %p.repuired
                    （仮）発送待ち
              .item__right-icon
                = icon('fa','angle-right')
        %li.panel

= render "shared/footer"

app/views/users/user_logout.html.haml
= render "shared/header"

.wrapper.clearfix
  = render "users/side_bar"

  .logout-main
    .logout-box
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "logout-btn"

= render "shared/footer"