config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'items#index'

  resources :items do
    member do
      get 'confirm'
      post 'pay'
    end
    collection do
    get 'set_parents'
    get 'set_children'
    get 'set_grandchildren'
    end
    resources :images, only: [:new, :create]
  end

  resources :cards, only: [:new, :create, :show, :destroy]


  get 'users', to: 'users#index'

  resources :users, only: [:new, :show] do
    collection do
      get 'user_logout'
    end
  end
end

app/views/shared/_category.html.haml
.category-box
  .parent
    - @parents.each do |parent|
      .parent-content
        = parent.name
        .child
          - parent.children.each do |child|
            .child-content
              = child.name
              .grandchild
                - child.children.each do |grandchild|
                  .grandchild-content
                    = grandchild.name

app/views/shared/_footer.html.haml
.app-dl
  .app-dl__inner
    %h2.app-dl__inner__title
      だれでもかんたん、人生を変えるフリマアプリ
    %p.app-dl__inner__text
      今すぐ無料ダウンロード！
    .app-dl__inner__icon
      = link_to "#" do
        = image_tag "/Download_on_the_Mac_App_Store_Badge_US-UK_RGB_blk_092917.svg", class: "app-store"
      = link_to "#" do
        = image_tag "/google-play-badge.png", class: "google-play"

%footer
  %ul.content-list
    %li.content-list__item
      %h2.content-list__item__head
        FURIMAについて
      %ul
        %li
          = link_to "#" do
            会社概要（運営会社）
        %li
          = link_to "#" do
            プライバシーポリシー
        %li
          = link_to "#" do
            FURIMA利用規約
        %li
          = link_to "#" do
            ポイントに関する特約
    %li.content-list__item
      %h2.content-list__item__head
        FURIMAを見る
      %ul
        %li
          = link_to "#" do
            カテゴリー一覧
        %li
          = link_to "#" do
            ブランド一覧
    %li.content-list__item
      %h2.content-list__item__head
        ヘルプ＆ガイド
      %ul
        %li
          = link_to "#" do
            FURIMAガイド
        %li
          = link_to "#" do
            FURIMAロゴ利用ガイドライン
        %li
          = link_to "#" do
            お知らせ
  .footer-logo
    = link_to root_path do
      = image_tag "/logo-white.png"
  %p
    &#64;FURIMA
- if user_signed_in?
  = link_to new_item_path do
    .exhibit-btn
      %span.exhibit-btn__text
        出品する
      = image_tag "/icon_camera.png", class: "exhibit-btn__icon"
- else
  = link_to new_user_session_path do
    .exhibit-btn
      %span.exhibit-btn__text
        出品する
      = image_tag "/icon_camera.png", class: "exhibit-btn__icon"

app/views/shared/_header.html.haml
%header
#request{action: request.path}
  .header-inner
    .header-inner__box
      %h1.header-innder__box__logo
        = link_to root_path do
          = image_tag "/logo.png"
      .header-inner__box__search
        %form
          %input.header-inner__box__search__input{placeholder: "キーワードから探す"}
          %button{type: "submit"}
            .header-inner__box__search__input__icon
              = image_tag "/icon-search 1.png"
    .header-inner__nav
      %ul.header-inner__nav__left
        %li.header-inner__nav__left__item
          = link_to "#" do
            #category-area
              カテゴリー
              .category-box
                = render partial: "shared/category"
        %li.header-inner__nav__left__item
          = link_to "#" do
            ブランド
      %ul.header-inner__nav__right
        - if user_signed_in?
          %li.header-inner__nav__right__item
            = link_to user_path(current_user) do
              マイページ
        - else
          %li.header-inner__nav__right__item
            = link_to new_user_session_path do
              ログイン
          %li.header-inner__nav__right__item
            = link_to new_user_path do
              新規会員登録

app/views/shared/_logo.html.haml
.logo
  = link_to root_path do
    = image_tag "/logo.png", size: "140x41"