config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'items#index'

  resources :items do
    member do
      get 'confirm'
      post 'pay'
    end
    collection do
    get 'set_parents'
    get 'set_children'
    get 'set_grandchildren'
    end
    resources :images, only: [:new, :create]
  end

  resources :cards, only: [:new, :create, :show, :destroy]


  get 'users', to: 'users#index'

  resources :users, only: [:new, :show] do
    collection do
      get 'user_logout'
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :area
  belongs_to :seller, class_name: 'User', optional: true
  belongs_to :buyer, class_name: 'User', optional: true
  has_many :images, dependent: :destroy
  belongs_to :category
  accepts_nested_attributes_for :images, allow_destroy: true

  validates :name, length: { minimum: 1, maximum: 40 }, presence: true
  validates :introduction, length: { minimum: 1, maximum: 1000 }, presence: true
  validates :condition, presence: true
  validates :area, presence: true
  validates :price, numericality: { only_integer: true , greater_than: 299, less_than: 10000000 }, presence: true
  validates :preparation_day, presence: true
  validates :postage, presence: true
  validates :status, presence: true
  validates :seller_id, presence: true
  validates :images, presence: true

  enum preparation_day: [:short, :middle, :long]
  enum postage: [:including, :noincluding]
  enum brand: [:chanel, :nike, :LouisVuitton, :supreme, :adidas, :ex]
  enum condition: [:zero, :one, :two, :three, :four, :five]
  enum size: [:xs, :x, :m, :l, :ll, :lxl]
  enum status: [:saling_item, :sold_item]
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only:[:edit, :update, :destroy, :show, :confirm, :pay]
  before_action :move_to_index, except:[:index, :show, :confirm]
  before_action :move_to_session, only:[:confirm]
  before_action :sold_check, only:[:confirm]

  def index
    @items = Item.order(created_at: :desc)
  end

  def new
    @item = Item.new
    @item.images.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to @item
    else
      @item.images.new
      render :new
    end
  end

  def edit
    if @item.seller_id != current_user.id
      redirect_to root_path, alert: "不正なアクセスです。"
    end

    grandchild_category = @item.category
    child_category = grandchild_category.parent

    @category_parent_array = Category.where(ancestry: nil)
    @category_children_array = Category.where(ancestry: child_category.ancestry)
    @category_grandchildren_array = Category.where(ancestry: grandchild_category.ancestry)
  end

  def update
    if @item.update(item_params)
      redirect_to @item
    else
      grandchild_category = @item.category
      child_category = grandchild_category.parent

      @category_parent_array = Category.where(ancestry: nil)
      @category_children_array = Category.where(ancestry: child_category.ancestry)
      @category_grandchildren_array = Category.where(ancestry: grandchild_category.ancestry)
      
      item = Item.find(params[:id])
      images = item.images
      @item.images = images
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to root_path
  end

  def show
  end

  def confirm
    if current_user.id == @item.seller_id
      redirect_to root_path
    end
    Payjp.api_key = Rails.application.credentials.payjp[:secret_key]
    if Card.where(user_id: current_user.id).blank?
      flash[:alert] = "クレジットカードを登録してください"
      redirect_to new_card_path
    else
      set_address
      card = Card.where(user_id: current_user.id).first
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
      @card_brand = @default_card_information.brand
      case @card_brand
      when "Visa"
        @card_image = "/visa.svg"
      when "JCB"
        @card_image = "/jcb.svg"
      when "MasterCard"
        @card_image = "/master-card.svg"
      when "American Express"
        @card_image = "/american_express.svg"
      when "Diners Club"
        @card_image = "/dinersclub.svg"
      when "Discover"
        @card_image = "/discover.svg"
      end
    end
  end

  def pay
    card = Card.where(user_id: current_user.id).first
    Payjp.api_key = Rails.application.credentials.payjp[:secret_key]
    Payjp::Charge.create(
      amount: @item.price,
      customer: card.customer_id,
      currency: 'jpy'
    )
    @item.update(buyer_id: current_user.id)
    redirect_to root_path
  end

  def set_parents
    @parents  = Category.where(ancestry: nil)
  end

  def set_children
    @children = Category.where(ancestry: params[:parent_id])
  end

  def set_grandchildren
    @grandchildren = Category.where(ancestry: params[:ancestry])
  end

  private
  def item_params
    params.require(:item).permit(:name, :introduction, :condition, :area_id, :category_id, :size, :price, :preparation_day, :postage, :brand, images_attributes: [:image, :_destroy, :id]).merge(seller_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def set_address
    @address = Address.find_by(user_id: current_user.id)
    @area = Area.find(@address.prefecture)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

  def move_to_session
    unless user_signed_in?
      redirect_to new_user_session_path
      flash[:alert] = "ログインしてください"
    end
  end

  def sold_check
    if @item.buyer_id != nil
      redirect_to root_path
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.haml
#request{action: request.path}
= form_for @item do |f|
  = render 'layouts/error_messages', model: f.object
  .new-wrapper__main
    .new-wrapper__main__title
      出品画像
      %span{class: "require"} 必須
    .new-wrapper__main__text
      最大10枚までアップロードできます
    .new-wrapper__main__image-box
      - if @item.persisted?
        - if @item.images.length < 5
          .previews
            - @item.images.each_with_index do |image, i|
              .previews__image
                = image_tag image.image.url, data: {index: i}, width: "120", height: "120", class: "previews__image__src"
                .remove-btn 削除
          %label{class: "new-wrapper__main__image-box__image-label", id: "image-label"}
            .new-wrapper__main__image-box__image-label__image-field
              = icon( 'fa', 'camera')
              .new-wrapper__main__imagde-box__image-label__image-field__text
                クリックしてファイルをアップロード
            = f.fields_for :images do |i|
              .js-file_group{data: {index: i.index}}
                = i.file_field :image, class: "js-file"
              - if @item.persisted?
                = i.check_box :_destroy, data:{ index: i.index }, class: 'hidden-destroy'
            - if @item.persisted?
              .js-file_group{data: {index: @item.images.count}}
                = file_field_tag :image, name: "item[images_attributes][#{@item.images.count}][image]", class: "js-file"
        - else
          .preview-first
            - @item.images[0..4].each_with_index do |image, i|
              .previews__image
                = image_tag image.image.url, data: {index: i}, width: "120", height: "120", class: "previews__image__src"
                .remove-btn 削除
          .previews
            - @item.images[5..9].each.with_index(5) do |image, i|
              .previews__image
                = image_tag image.image.url, data: {index: i}, width: "120", height: "120", class: "previews__image__src"
                .remove-btn 削除
          %label{class: "new-wrapper__main__image-box__image-label", id: "image-label"}
            .new-wrapper__main__image-box__image-label__image-field{ style: "display: none"}
              = icon( 'fa', 'camera')
              .new-wrapper__main__imagde-box__image-label__image-field__text
                クリックしてファイルをアップロード
            - if 5 <= @item.images.length && @item.images.length < 10
              .new-wrapper__main__image-box__image-label__image-field{ id: "image-field-second"}
                = icon( 'fa', 'camera')
                .new-wrapper__main__imagde-box__image-label__image-field__text
                  クリックしてファイルをアップロード
            - else
              .new-wrapper__main__image-box__image-label__image-field{ id: "image-field-second", style: "display: none;"}
                = icon( 'fa', 'camera')
                .new-wrapper__main__imagde-box__image-label__image-field__text
                  クリックしてファイルをアップロード
            = f.fields_for :images do |i|
              .js-file_group{data: {index: i.index}}
                = i.file_field :image, class: "js-file"
              - if @item.persisted?
                = i.check_box :_destroy, data:{ index: i.index }, class: 'hidden-destroy'
            - if @item.persisted?
              .js-file_group{data: {index: @item.images.count}}
                = file_field_tag :image, name: "item[images_attributes][#{@item.images.count}][image]", class: "js-file"
      - else
        .previews
        %label{class: "new-wrapper__main__image-box__image-label", id: "image-label"}
          .new-wrapper__main__image-box__image-label__image-field
            = icon( 'fa', 'camera')
            .new-wrapper__main__imagde-box__image-label__image-field__text
              クリックしてファイルをアップロード
          = f.fields_for :images do |i|
            .js-file_group{data: {index: i.index}}
              = i.file_field :image, class: "js-file"
            - if @item.persisted?
              = i.check_box :_destroy, data:{ index: i.index }, class: 'hidden-destroy'
          - if @item.persisted?
            .js-file_group{data: {index: @item.images.count}}
              = file_field_tag :image, name: "item[images_attributes][#{@item.images.count}][image]", class: "js-file"
  .new-wrapper__main
    .new-wrapper__main__title
      商品名
      %span{class: "require"} 必須
    = f.text_field :name, class: "new-wrapper__main__input-text", placeholder: "40文字まで"
    .new-wrapper__main__title.spacing
      商品の説明
      %span{class: "require"} 必須
    = f.text_area :introduction, class: "new-wrapper__main__input-textarea", placeholder: "商品の説明(必須 1,000文字以内)\n（色、素材、重さ、定価、注意点など）\n\n例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"
  .new-wrapper__main
    .new-wrapper__main__subtitle
      商品の詳細
    .new-wrapper__main__title
      カテゴリー
      %span{class: "require"} 必須
    - if @item.persisted?
      #category-preview
        = f.select :category, options_for_select( @category_parent_array.map{|c|[c[:name], c[:id], {}]}, @item.category.parent.parent.id), {}, {class: 'new-wrapper__main__input-select select-parent', id: 'select-parent', style: 'margin-bottom: 10px;'}
        = f.select :category, options_for_select( @category_children_array.map{|c|[c[:name], c[:id], {}]}, @item.category.parent.id), {}, {class: 'new-wrapper__main__input-select select-child', id: 'select-parent', style: 'margin-bottom: 10px;'}
        = f.select :category, options_for_select( @category_grandchildren_array.map{|c|[c[:name], c[:id], {}]}, @item.category.id), {}, {class: 'new-wrapper__main__input-select select-grandchild', id: 'item_category_id'}
    - else
      #category-select
    .new-wrapper__main__title
      サイズ
      %span{class: "any"} 任意
    = f.select :size, Item.sizes_i18n.invert {}, prompt: "選択してください"
    .new-wrapper__main__title.spacing
      ブランド
      %span{class: "any"} 任意
    = f.select :brand, Item.brands_i18n.invert {}, prompt: "選択してください"
  .new-wrapper__main
    .new-wrapper__main__title.spacing
      商品の状態
      %span{class: "require"} 必須
    = f.select :condition, Item.conditions_i18n.invert {}, prompt: "選択してください"
  .new-wrapper__main
    .new-wrapper__main__subtitle
      配送について
    .new-wrapper__main__title
      配送料の負担
      %span{class: "require"} 必須
    = f.select :postage, Item.postages_i18n.invert {}, prompt: "選択してください"
    .new-wrapper__main__title.spacing
      発送元の地域
      %span{class: "require"} 必須
    = f.collection_select :area_id, Area.all, :id, :name, prompt: "選択してください"
    .new-wrapper__main__title.spacing
      発送までの日数
      %span{class: "require"} 必須
    = f.select :preparation_day, Item.preparation_days_i18n.invert {}, prompt: "選択してください"
  .new-wrapper__main
    .new-wrapper__main__subtitle
      価格（¥300〜9,999,999）
    .new-wrapper__main__title.float-left
      販売価格
      %span{class: "require"} 必須
    .new-wrapper__main__input-price.float-right
      ¥
      = f.number_field :price, class: "new-wrapper__main__input-price__input", placeholder: "0"
    .spacing
      - if user_signed_in?
        = f.submit class:"new-wrapper__main__submit"
      - else
        = link_to "投稿する", new_user_session_path, class: "new-wrapper__main__submit"
    .new-wrapper__main__caution
      禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。

app/views/items/confirm.html.haml
.header
  .header__top
    = render "shared/logo"

%main.check-buy
  %section.check-buy__content
    %h2.check-buy__content__title
      購入内容の確認
    %section.check-buy__content__item
      .check-buy__content__item__inner
        .check-buy__content__item__inner__box
          %h3.check-buy__content__item__inner__box__image
            = image_tag @item.images.first.image.url, class: "image-main"
          .check-buy__content__item__inner__box__detail
            %p.check-buy__content__item__inner__box__detail__name
              = @item.name
            %p.check-buy__content__item__inner__box__detail__price
              = "¥#{@item.price.to_s(:delimited)} (税込)"

    %section.check-buy__content__item
      .check-buy__content__item__inner
        .check-buy__content__item__inner__form
          %ul.check-buy__content__item__inner__form__price
            %li.check-buy__content__item__inner__form__price__box
              .check-buy__content__item__inner__form__price__box__head
                支払い金額
              .check-buy__content__item__inner__form__price__box__body
                

          %section.check-buy__content__item__inner__form__payment
            .check-buy__content__item__inner__form__payment__inner
              %h3.check-buy__content__item__inner__form__payment__box__title
                支払い方法
              - if @default_card_information.blank?
                %br /
              - else
                %p.check-buy__content__item__inner__form__payment__box__title__under
                  = "**** **** **** " + @default_card_information.last4
                  %br
                    - exp_month = @default_card_information.exp_month.to_s
                    - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
                    = exp_month + " / " + exp_year
              .card_box
                = image_tag "#{@card_image}",width:'30',height:'30'
            .change_text_color_blue

          %section.check-buy__content__item__inner__form__delivery
            .check-buy__content__item__inner__form__delivery__inner
              %h3.check-buy__content__item__inner__form__delivery__box__title
                配送先
                %p.check-buy__content__item__inner__form__delivery__box__title__under
                = "〒" + @address.post_code
                %br
                = @area.name
                = @address.city
                = @address.address
                = @address.apartment
                %br
                = @address.tel_number

          %section.check-buy__content__item__inner__form__fix
            .check-buy__content__item__inner__form__fix__btn
              = form_with(url: pay_item_path, local: true, method: :post) do |f|
                = f.submit "購入する"

= render partial: "shared/user_footer"

app/views/items/edit.html.haml
.header
  .header__top
    = render "shared/logo"

.new-wrapper
  = render partial: 'form'

.footer
  .footer__top
    .privacy
      = link_to "#" do
        プライバシーポリシー
    .rule
      = link_to "#" do
        フリマ利用規約
    .commercial
      = link_to "#" do
        特定商取引に関する表記
  .footer__copyright ©︎ Furima

app/views/items/index.html.haml
= render partial: "shared/header"
%main

  %section.main-visual
    .main-visual__content
      %h2.main-visual__content__title
        人生を変えるフリマアプリ
      %p.main-visual__content__text
        FURIMAはだれでもかんたんに出品・購入できる
        %br
        フリマアプリです
      .main-visual__content__btn
        = link_to "#" do
          = image_tag "/Download_on_the_Mac_App_Store_Badge_US-UK_RGB_blk_092917.svg", class: "app-store"
        = link_to "#" do
          = image_tag "/google-play-badge.png", class: "google-play"
    .main-visual__image

  %section.cause
    %h2.cause__title
      FURIMAが選ばれる3つの理由
    %ul.cause__list
      %li.cause__list__item
        .cause__list__item__image
          %span.cause__list__item__image__number
            1
          = image_tag "/pict-reason-01.jpg"
        %h3.cause__list__item__title
          %span 3分
          ですぐに出品
        %p.cause__list__item__text
          スマホで入力するだけで簡単に出品できる！
      %li.cause__list__item
        .cause__list__item__image
          %span.cause__list__item__image__number
            2
          = image_tag "/pict-reason-02.jpg"
        %h3.cause__list__item__title
          %span シンプル
          で使いやすい
        %p.cause__list__item__text
          めんどくさい入力は必要なく、検索も購入もスムーズ！
      %li.cause__list__item--last
        .cause__list__item__image
          %span.cause__list__item__image__number
            3
          = image_tag "/pict-reason-03.jpg"
        %h3.cause__list__item__title
          手数料
          %span 業界最安
        %p.cause__list__item__text
          最大3%でお得に出品&購入！

  %section.sub-visual
    .sub-visual__content
      %h2.sub-visual__content__title
        会員数日本一位
      %p.sub-visual__content__text
        FURIMAは、フリマアプリで最も人気。
        %br
        出品・購入回数も業界最多です！
        %br
        ほしかったあの商品に出会えるかもしれません。
      .sub-visual__content__btn
        = link_to "#" do
          = image_tag "/Download_on_the_Mac_App_Store_Badge_US-UK_RGB_blk_092917.svg", class: "app-store"
        = link_to "#" do
          = image_tag "/google-play-badge.png", class: "google-play"

  %section.feature
    %h2.feature__title
      FURIMAの特徴
    .feature__item
      .feature__item__list
        %figure.feature__item__list__image
          = image_tag "/icon-01.png"
        %h3.feature__item__list__title
          簡単に売り買いできる
        %p.feature__item__list__text
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      .feature__item__list
        %figure.feature__item__list__image
          = image_tag "/icon-03.png"
        %h3.feature__item__list__title
          売上金は即日振込みに対応
        %p.feature__item__list__text
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします！
      .feature__item__list
        %figure.feature__item__list__image
          = image_tag "/icon-04.png"
        %h3.feature__item__list__title
          様々な支払いに対応
        %p.feature__item__list__text
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。

  %section.pickup-item
    %h2.pickup-item__title
      商品一覧
    .pickup-item__box
      .pickup-item__box__head
        = link_to "#" do
          %h3.pickup-item__box__head__title
            新規投稿商品
      .pickup-item__box__list
        .pickup-item__box__list__item
          - @items[0..2].each do |item|
            = link_to item_path(item.id) do
              %figure.pickup-item__box__list__item__image
                = image_tag item.images.first.image.url
              .pickup-item__box__list__item__body
                %h3.pickup-item__box__list__item__body__name
                  = item.name
                .pickup-item__box__list__item__body__detail
                  %ul
                    %li
                      = item.price
                    %li
                      %i.fa.fa-star
                      0
                  %p
                    (税込)
              -if item.buyer_id.present?
                .sold-out-display
                  .sold-out-display__inner
                    SOLD
= render partial: "shared/footer"

app/views/items/new.html.haml
.header
  .header__top
    = render "shared/logo"

.new-wrapper
  = render partial: 'form'

.footer
  .footer__top
    .privacy
      = link_to "#" do
        プライバシーポリシー
    .rule
      = link_to "#" do
        フリマ利用規約
    .commercial
      = link_to "#" do
        特定商取引に関する表記
  .footer__copyright ©︎ Furima

app/views/items/show.html.haml
= render partial: "shared/header"
.main
  .main__showMain
    .main__contentLeftqq
    .main__showMain__contentRight
      .main__showMain__contentRight__topContent
        .main__showMain__contentRight__topContent__itemBox
        %h1.main__showMain__contentRight__topContent__itemBox__name
          = @item.name
        .main__showMain__contentRight__topContent__itemBox__itemInfo__body
          %ul.main__showMain__contentRight__topContent__itemBox__itemInfo__body--main-image
            %li
              = image_tag @item.images.first.image.url, class: "image-main"
          %ul.main__showMain__contentRight__topContent__itemBox__itemInfo__body--sub-image
            - @item.images.each do |f|
              %li
                = image_tag f.image.url,class: "image_sub"
        .main__showMain__contentRight__topContent__itemBox__itemInfo__price
          %span
            ¥
            = @item.price
          .main__showMain__contentRight__topContent__itemBox__itemInfo__price__itemBox__price-detail
            %span
              (税込）
            %span
              送料込み
        .main__showMain__contentRight__topContent__itemBox__itemDetail
          =  @item.introduction
        .main__showMain__contentRight__topContent__itemBox__table
          %table
            %tbody
              %tr
                %th 出品者
                %td 
                  = @item.seller.nickname
              %tr
                %th カテゴリー
                %td
                  =link_to '#' do
                    = @item.category.parent.parent.name
                  %br/
                  =link_to '#' do
                    = @item.category.parent.name
                  %br/
                  =link_to '#' do
                    = @item.category.name
              %tr
                %th ブランド
                %td
                  - if @item.brand.present?
                    = @item.brand_i18n
              %tr
                %th 商品のサイズ
                %td
                  - if @item.size.present?
                    = @item.size_i18n
              %tr
                %th 商品の状態
                %td
                  = @item.condition_i18n
              %tr
                %th 配送料の負担
                %td
                  = @item.postage_i18n
              %tr
                %th 発送元の地域
                %td
                  = link_to @item.area.name
              %tr

                %th 発送日の目安
                %td
                  = @item.preparation_day_i18n
      -# 出品者にしか商品の情報編集・削除のリンクが踏めないようになっている
      - if user_signed_in? && current_user.id == @item.seller_id
        .main__showMain__contentRight__topContent__itemBox__linklist
          = link_to edit_item_path(@item) do
            .main__showMain__contentRight__topContent__itemBox__linklist__edit 商品の編集
          = link_to item_path(@item.id), method: :delete do
            .main__showMain__contentRight__topContent__itemBox__linklist__delete この商品を削除する
      - elsif @item.buyer_id.present?
        .main__showMain__contentRight__topContent__itemBox__inklist
          .main__showMain__contentRight__topContent__itemBox__linklist__sold この商品は販売済みです
      - else
        .main__showMain__contentRight__topContent__itemBox__inklist
          = link_to confirm_item_path(@item) do
            .main__showMain__contentRight__topContent__itemBox__linklist__buy 商品を購入
        .main__showMain__contentRight__topContent__itemBox__optionalArea
          %ul
            %li.main__showMain__contentRight__topContent__itemBox__optionalArea__likeBtn
              %i.fa.fa-star
              お気に入り 0
          %ul.main__showMain__contentRight__topContent__itemBox__optionalArea__optional
            %li.main__showMain__contentRight__topContent__itemBox__optionalArea__optional__optionalBtn
              =link_to  '#' do
                %i.fas.fa-flag
                不適切な商品の通報
        .main__showMain__contentRight__topContent__commentBox
          %ul.main__showMain__contentRight__topContent__commentBox__commentContents
          %form#new_comment.new_comment{"accept-charset": "UTF-8", action: "#", method: "post"}
            %input{name: "utf8", type: "hidden", value: "✓"}/
            %input{name: "authenticity_token", type: "hidden", value: "gyvWrYv/zM4S5LsgDn3L8BuUZAQ1lpewtQWNPCu+HPL3KHSTLkZTWoGbARzyVOYgdUDUcN53biKkBNXxiuCCbQ=="}/
            %textarea#comment_body{name: "comment[body]", required: "required"}
            %p.main__showMain__contentRight__topContent__commentBox__commentContents__noticeMsg
              相手のことを考え丁寧なコメントを心がけましょう。
              %br/
              不快な言葉遣い等は退会処分となる事があります。
            %button.main__showMain__contentRight__topContent__commentBox__commentContents__commentBtn{name: "button", typ: "submit"}
              %i.fa.fa-comment
              コメントする
          %ul.main__showMain__contentRight__links
            %li
              =link_to  '#' do
                %i.fa.fa-angle-left
                %span
                  前の商品
            %li
              =link_to  '#' do
                %span
                  後ろの商品
                  %i.fa.fa-angle-right
        .main__showMain__contentRight__relatedItems
          =link_to  '#' do
            レディースをもっと見る
= render partial: "shared/footer"