config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'items#index'

  resources :items do
    member do
      get 'confirm'
      post 'pay'
    end
    collection do
    get 'set_parents'
    get 'set_children'
    get 'set_grandchildren'
    end
    resources :images, only: [:new, :create]
  end

  resources :cards, only: [:new, :create, :show, :destroy]


  get 'users', to: 'users#index'

  resources :users, only: [:new, :show] do
    collection do
      get 'user_logout'
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  validates  :user_id, :customer_id, :card_id, presence: true
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  require "payjp"

  def new
    if user_signed_in?
      card = Card.where(user_id: current_user.id)
      redirect_to card_path(current_user.id) if card.exists?
    else
      flash[:alert] = "ログインしてください"
      redirect_to new_user_session_path
    end
  end

  def create
    Payjp.api_key = Rails.application.credentials.payjp[:secret_key]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
        card: params['payjp-token'],
        metadata: {user_id: current_user.id}
        ) 
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to card_path(@card)
        flash[:notice] = 'クレジットカードの登録が完了しました'
      else
        redirect_to action: "pay"
        flash[:alert] = 'クレジットカード登録に失敗しました'
      end
    end
  end

  def destroy
    card = Card.where(user_id: current_user.id).first
    if card.blank?
    else
      Payjp.api_key = Rails.application.credentials.payjp[:secret_key]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
    redirect_to root_path
  end

  def show
    card = Card.where(user_id: current_user.id).first
    if card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = Rails.application.credentials.payjp[:secret_key]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
    @card_brand = @default_card_information.brand
    case @card_brand
    when "Visa"
      @card_image = "/visa.svg"
    when "JCB"
      @card_image = "/jcb.svg"
    when "MasterCard"
      @card_image = "/master-card.svg"
    when "American Express"
      @card_image = "/american_express.svg"
    when "Diners Club"
      @card_image = "/dinersclub.svg"
    when "Discover"
      @card_image = "/discover.svg"
    end
  end
end

app/views/cards/new.html.haml
= render "shared/header"

.wrapper.clearfix
  = render "users/side_bar"

  .card-main
    %h3.registration-title
      クレジットカード情報入力
    .registration-box
      .registration-box__form
        = form_with model: @card, url: cards_path, local: true, html: { id: 'charge-form',name: 'inputForm' } do |f|
          .card-input
            %p.card-number
              カード番号
            %p.repuired
              必須
          = f.text_field :card_number, id: "card_number",class: "number-input", placeholder: "半角数字のみ"
          %ul.credit-card
            %li.credit-card__card-list
              = image_tag "/visa.svg", size: "30x30"
            %li.credit-card__card-list
              = image_tag "/master-card.svg", size: "30x30"
            %li.credit-card__card-list
              = image_tag "/saison-card.svg", size: "30x30"
            %li.credit-card__card-list
              = image_tag "/jcb.svg", size: "30x30"
            %li.credit-card__card-list
              = image_tag "/dinersclub.svg", size: "30x30"
            %li.credit-card__card-list
              = image_tag "/discover.svg", size: "30x30"
            %li.credit-card__card-list
              = image_tag "/american_express.svg", size: "30x30"
          .card-data
            %p.expiration
              有効期限
            %p.repuired
              必須
          .date
            = f.select :exp_month,[["01",1],["02",2],["03",3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12]],{} , id:"exp_month", class: "card-date__month"
            %span 月
            = f.select :exp_year, [["20",2020],["21",2021],["22",2022],["23",2023],["24",2024],["25",2025],["26",2026],["27",2027],["28",2028],["29",2029],["30",2030]],{} ,id:"exp_year", class: "card-date__year"
            %span 年
          #card_token
          .card-security
            %p.security-code
              セキュリティコード
            %p.repuired
              必須
          = f.password_field :security_code, id: "cvc", class: "security-input", placeholder: "カード背面4桁もしくは3桁の番号"
          = link_to "カード裏面の番号とは？", "#", class: "card-info"
          = f.submit "追加する", class: "submit-btn", id: "token_submit"

= render "shared/footer"

app/views/cards/show.html.haml
= render "shared/header"

.wrapper.clearfix
  = render "users/side_bar"

  .credit_card__list
    .credit_card__list__title
      支払い方法
    .credit_card__list__frame
      .credit_card_info
        .credit_card_info__brand
          = image_tag "#{@card_image}",width:'30',height:'30'
        .credit_card_info__numbers
          .number
            = "**** **** **** " + @default_card_information.last4
          .expiration_date
            .expiration_date__title
              有効期限
            .expiration_date__info
            - exp_month = @default_card_information.exp_month.to_s
            - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
        .destroy__function
          .destroy__function__link
            = link_to card_path, method: :delete do
              .destroy__btn
                削除する

= render "shared/footer"